# Generated by Django 2.2.12 on 2020-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200425_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='data',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(default='asd', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail',
            field=models.ImageField(default='asd', upload_to='img/'),
            preserve_default=False,
        ),
    ]
