# Generated by Django 2.2.12 on 2020-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200425_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
