# Generated by Django 2.2.12 on 2020-04-25 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200425_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
