# Generated by Django 2.2.12 on 2020-04-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imagemodel_ts'),
        ('flock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.ImageModel'),
        ),
    ]
