# Generated by Django 2.2.12 on 2020-04-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imagemodel_ts'),
        ('flock', '0002_user_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='featured',
        ),
        migrations.AddField(
            model_name='user',
            name='featured',
            field=models.ManyToManyField(blank=True, to='images.ImageModel'),
        ),
    ]
