# Generated by Django 2.2.12 on 2020-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='data',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
