# Generated by Django 2.2.12 on 2020-05-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0004_auto_20200504_1951'),
        ('images', '0005_imagemodel_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flock.User'),
        ),
    ]
