# Generated by Django 2.2.12 on 2020-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_imagemodel_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
