# Generated by Django 2.2.12 on 2020-05-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0003_auto_20200425_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_image_height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='user',
            name='max_image_width',
            field=models.IntegerField(default=150),
        ),
    ]
