# Generated by Django 2.2.12 on 2020-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0004_auto_20200504_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items_per_page',
            field=models.IntegerField(default=20),
        ),
    ]
