# Generated by Django 2.1.15 on 2020-06-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0005_user_items_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_image_height',
            field=models.IntegerField(default=110),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_image_width',
            field=models.IntegerField(default=110),
        ),
    ]
